version: '3.8'

services:
  acestream:
    image: jopsis/acestream:arm
    container_name: acestream-arm
    privileged: true
    ports:
      - "8621:8621"
      - "6878:6878"
    restart: unless-stopped
    # Uncomment to use custom configuration
    # volumes:
    #   - ./acestream.conf:/acestream.engine/acestream.conf
